/* AUTO-GENERATED by build_3dsx.ps1 - sends stderr and SDL_Log output to the emulator/debug log. */
#include <3ds.h>
#include <stdio.h>
#include <SDL.h>
__attribute__((constructor)) static void dr_debug_init(void)
{
    consoleDebugInit(debugDevice_SVC);
    setvbuf(stderr, NULL, _IONBF, 0);
    SDL_LogSetAllPriority(SDL_LOG_PRIORITY_VERBOSE);
    fprintf(stderr, "[debug_log] started\n");
}