/* AUTO-GENERATED by build_3dsx.ps1 - LAN multiplayer is not available on the 3DS. */
int sendPlayerMovePacket() { return 0; }
int recvLanPacket() { return 0; }
int sendGameOverPacket() { return 0; }
int hostGame() { return 0; }
int joinGame() { return 0; }
void *lanClientSocket = 0;
