/* AUTO-GENERATED by build_3dsx.ps1 - stand-in for SDL2_net, which does not exist on the 3DS.
   Types and prototypes only, so code that includes <SDL_net.h> still compiles. */
#ifndef DR3DS_SDL_NET_SHIM_H
#define DR3DS_SDL_NET_SHIM_H
#include <SDL.h>
#define DR_NO_NET 1
#define SDLNET_MAX_UDPCHANNELS 32
typedef struct { Uint32 host; Uint16 port; } IPaddress;
typedef struct _TCPsocket *TCPsocket;
typedef struct _UDPsocket *UDPsocket;
typedef struct _SDLNet_SocketSet *SDLNet_SocketSet;
typedef struct _SDLNet_GenericSocket *SDLNet_GenericSocket;
typedef struct { int channel; Uint8 *data; int len; int maxlen; int status; IPaddress address; } UDPpacket;
int SDLNet_Init(void);
void SDLNet_Quit(void);
const char *SDLNet_GetError(void);
int SDLNet_ResolveHost(IPaddress *address, const char *host, Uint16 port);
const char *SDLNet_ResolveIP(const IPaddress *ip);
TCPsocket SDLNet_TCP_Open(IPaddress *ip);
TCPsocket SDLNet_TCP_Accept(TCPsocket server);
IPaddress *SDLNet_TCP_GetPeerAddress(TCPsocket sock);
int SDLNet_TCP_Send(TCPsocket sock, const void *data, int len);
int SDLNet_TCP_Recv(TCPsocket sock, void *data, int maxlen);
void SDLNet_TCP_Close(TCPsocket sock);
SDLNet_SocketSet SDLNet_AllocSocketSet(int maxsockets);
void SDLNet_FreeSocketSet(SDLNet_SocketSet set);
int SDLNet_AddSocket(SDLNet_SocketSet set, SDLNet_GenericSocket sock);
int SDLNet_DelSocket(SDLNet_SocketSet set, SDLNet_GenericSocket sock);
int SDLNet_CheckSockets(SDLNet_SocketSet set, Uint32 timeout);
int SDLNet_SocketReady(void *sock);
#define SDLNet_TCP_AddSocket(set, sock) SDLNet_AddSocket(set, (SDLNet_GenericSocket)(sock))
#define SDLNet_TCP_DelSocket(set, sock) SDLNet_DelSocket(set, (SDLNet_GenericSocket)(sock))
#define SDLNet_UDP_AddSocket(set, sock) SDLNet_AddSocket(set, (SDLNet_GenericSocket)(sock))
#define SDLNet_UDP_DelSocket(set, sock) SDLNet_DelSocket(set, (SDLNet_GenericSocket)(sock))
#define SDLNet_SocketReady(sock) SDLNet_SocketReady((void *)(sock))
UDPsocket SDLNet_UDP_Open(Uint16 port);
void SDLNet_UDP_Close(UDPsocket sock);
int SDLNet_UDP_Send(UDPsocket sock, int channel, UDPpacket *packet);
int SDLNet_UDP_Recv(UDPsocket sock, UDPpacket *packet);
UDPpacket *SDLNet_AllocPacket(int size);
void SDLNet_FreePacket(UDPpacket *packet);
static inline void SDLNet_Write16(Uint16 value, void *area) { Uint8 *p = (Uint8 *)area; p[0] = (Uint8)(value >> 8); p[1] = (Uint8)value; }
static inline void SDLNet_Write32(Uint32 value, void *area) { Uint8 *p = (Uint8 *)area; p[0] = (Uint8)(value >> 24); p[1] = (Uint8)(value >> 16); p[2] = (Uint8)(value >> 8); p[3] = (Uint8)value; }
static inline Uint16 SDLNet_Read16(const void *area) { const Uint8 *p = (const Uint8 *)area; return (Uint16)((p[0] << 8) | p[1]); }
static inline Uint32 SDLNet_Read32(const void *area) { const Uint8 *p = (const Uint8 *)area; return ((Uint32)p[0] << 24) | ((Uint32)p[1] << 16) | ((Uint32)p[2] << 8) | (Uint32)p[3]; }
#endif