/* AUTO-GENERATED by build_3dsx.ps1 - every network call fails cleanly (Init "succeeds" so startup code keeps going). */
#include <SDL_net.h>
#include <stddef.h>
#undef SDLNet_SocketReady
int SDLNet_Init(void) { return 0; }
void SDLNet_Quit(void) {}
const char *SDLNet_GetError(void) { return "SDL2_net is not available on the 3DS"; }
int SDLNet_ResolveHost(IPaddress *a, const char *h, Uint16 p) { (void)a; (void)h; (void)p; return -1; }
const char *SDLNet_ResolveIP(const IPaddress *ip) { (void)ip; return ""; }
TCPsocket SDLNet_TCP_Open(IPaddress *ip) { (void)ip; return NULL; }
TCPsocket SDLNet_TCP_Accept(TCPsocket s) { (void)s; return NULL; }
IPaddress *SDLNet_TCP_GetPeerAddress(TCPsocket s) { (void)s; return NULL; }
int SDLNet_TCP_Send(TCPsocket s, const void *d, int n) { (void)s; (void)d; (void)n; return -1; }
int SDLNet_TCP_Recv(TCPsocket s, void *d, int n) { (void)s; (void)d; (void)n; return -1; }
void SDLNet_TCP_Close(TCPsocket s) { (void)s; }
SDLNet_SocketSet SDLNet_AllocSocketSet(int n) { (void)n; return NULL; }
void SDLNet_FreeSocketSet(SDLNet_SocketSet s) { (void)s; }
int SDLNet_AddSocket(SDLNet_SocketSet s, SDLNet_GenericSocket k) { (void)s; (void)k; return -1; }
int SDLNet_DelSocket(SDLNet_SocketSet s, SDLNet_GenericSocket k) { (void)s; (void)k; return -1; }
int SDLNet_CheckSockets(SDLNet_SocketSet s, Uint32 t) { (void)s; (void)t; return -1; }
int SDLNet_SocketReady(void *k) { (void)k; return 0; }
UDPsocket SDLNet_UDP_Open(Uint16 p) { (void)p; return NULL; }
void SDLNet_UDP_Close(UDPsocket s) { (void)s; }
int SDLNet_UDP_Send(UDPsocket s, int c, UDPpacket *p) { (void)s; (void)c; (void)p; return 0; }
int SDLNet_UDP_Recv(UDPsocket s, UDPpacket *p) { (void)s; (void)p; return -1; }
UDPpacket *SDLNet_AllocPacket(int n) { (void)n; return NULL; }
void SDLNet_FreePacket(UDPpacket *p) { (void)p; }